class QuoteProvider {
  static List<String> quotes = [
    "Your body hears everything your mind says.",
"Embrace the journey to a healthier you.",
"Every small step is progress.",
"Wellness is the key to a happy life.",
"Fuel your body, nourish your soul.",
"Progress, not perfection.",
"Invest in yourself daily.",
"Your health is an investment, not an expense.",
"Today's choices, tomorrow's health.",
"Wellness is a lifestyle, not a quick fix.",
"Celebrate progress, not perfection.",
"A healthy outside starts from the inside.",
"Nourish your body, mind, and spirit.",
"Small changes, big results.",
"Listen to your body, it knows best.",
"Wellness is the first wealth.",
"You are what you eat – choose wisely.",
"Be stronger than your excuses.",
"Healthy habits create a healthy life.",
"Your health is your wealth.",
"Find joy in the journey to wellness.",
"Start where you are, use what you have, do what you can.",
"Health is not about the weight you lose, but the life you gain.",
"Respect your body. It's the only one you get.",
"Believe in the power of small changes.",
"Wellness is a gift you give yourself.",
"Make time for self-care.",
"A healthy outside starts from the inside.",
"Mindset is everything.",
"Don't wish for it, work for it.",
"Wellness is the result of small daily efforts.",
"Health is the greatest wealth.",
"Celebrate every victory, no matter how small.",
"Your body can stand almost anything. It's your mind that you have to convince.",
"Wellness is the key to unlocking your full potential.",
"Love yourself enough to live a healthy lifestyle.",
"You are what you eat, so don't be fast, cheap, easy, or fake.",
"Stay positive, work hard, make it happen.",
"The only bad workout is the one that didn't happen.",
"Healthy habits, happy life.",
"You're only one workout away from a good mood.",
"Start each day with a grateful heart and a healthy choice.",
"Wellness is the best kind of wealth.",
"Your health is an investment, not an expense.",
"Fuel your body with kindness.",
"Wellness is the key to unlocking your full potential.",
"Progress, not perfection.",
"A healthy outside starts from the inside.",
"Take care of your body; it's the only place you have to live.",
"Wellness is a state of mind.",
"Your body hears everything your mind says.",
"The journey of a thousand miles begins with one step.",
"Wellness is a daily pursuit.",
"Believe in yourself and all that you are.",
"Wellness is the first step to happiness.",
"Small changes, big results.",
"Your health is your most valuable asset.",
"Wellness is the best kind of beauty.",
"Celebrate progress, not perfection.",
"Your health is an investment, not an expense.",
"Choose health, happiness will follow.",
"Nourish your body, feed your soul.",
"Progress, not perfection.",
"Invest in your health – it pays the best interest.",
"Wellness is the key to a vibrant life.",
"Your body is a reflection of your lifestyle.",
"Love yourself enough to live a healthy lifestyle.",
"Wellness is the journey, not the destination.",
"Take care of your body; it's the only place you have to live.",
"Wellness is a balance of mind, body, and spirit.",
"Celebrate every small victory on your wellness journey.",
"A healthy outside starts from the inside.",
"Wellness is the first step to happiness.",
"Your health is your wealth.",
"Wellness is not a destination, it's a journey.",
"Small steps lead to big results.",
"Choose health, happiness will follow.",
"Your body is your temple; treat it with respect.",
"Progress, not perfection.",
"Wellness is a lifestyle, not a quick fix.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a journey, not a destination.",
"Choose health, happiness will follow.",
"Invest in your health – it pays the best interest.",
"Wellness is the key to a vibrant life.",
"Your health is your most valuable asset.",
"Love yourself enough to live a healthy lifestyle.",
"Wellness is the journey, not the destination.",
"Celebrate every small victory on your wellness journey.",
"A healthy outside starts from the inside.",
"Wellness is the first step to happiness.",
"Your body is a reflection of your lifestyle.",
"Progress, not perfection.",
"Choose health, happiness will follow.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a lifestyle, not a quick fix.",
"Progress, not perfection.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a journey, not a destination.",
"Choose health, happiness will follow.",
"Invest in your health – it pays the best interest.",
"Wellness is the key to a vibrant life.",
"Your health is your most valuable asset.",
"Love yourself enough to live a healthy lifestyle.",
"Wellness is the journey, not the destination.",
"Celebrate every small victory on your wellness journey.",
"A healthy outside starts from the inside.",
"Wellness is the first step to happiness.",
"Your body is a reflection of your lifestyle.",
"Progress, not perfection.",
"Choose health, happiness will follow.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a lifestyle, not a quick fix.",
"Progress, not perfection.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a journey, not a destination.",
"Choose health, happiness will follow.",
"Invest in your health – it pays the best interest.",
"Wellness is the key to a vibrant life.",
"Your health is your most valuable asset.",
"Love yourself enough to live a healthy lifestyle.",
"Wellness is the journey, not the destination.",
"Celebrate every small victory on your wellness journey.",
"A healthy outside starts from the inside.",
"Wellness is the first step to happiness.",
"Your body is a reflection of your lifestyle.",
"Progress, not perfection.",
"Choose health, happiness will follow.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a lifestyle, not a quick fix.",
"Progress, not perfection.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a journey, not a destination.",
"Choose health, happiness will follow.",
"Invest in your health – it pays the best interest.",
"Wellness is the key to a vibrant life.",
"Your health is your most valuable asset.",
"Love yourself enough to live a healthy lifestyle.",
"Wellness is the journey, not the destination.",
"Celebrate every small victory on your wellness journey.",
"A healthy outside starts from the inside.",
"Wellness is the first step to happiness.",
"Your body is a reflection of your lifestyle.",
"Progress, not perfection.",
"Choose health, happiness will follow.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a lifestyle, not a quick fix.",
"Progress, not perfection.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a journey, not a destination.",
"Choose health, happiness will follow.",
"Invest in your health – it pays the best interest.",
"Wellness is the key to a vibrant life.",
"Your health is your most valuable asset.",
"Love yourself enough to live a healthy lifestyle.",
"Wellness is the journey, not the destination.",
"Celebrate every small victory on your wellness journey.",
"A healthy outside starts from the inside.",
"Wellness is the first step to happiness.",
"Your body is a reflection of your lifestyle.",
"Progress, not perfection.",
"Choose health, happiness will follow.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a lifestyle, not a quick fix.",
"Progress, not perfection.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a journey, not a destination.",
"Choose health, happiness will follow.",
"Invest in your health – it pays the best interest.",
"Wellness is the key to a vibrant life.",
"Your health is your most valuable asset.",
"Love yourself enough to live a healthy lifestyle.",
"Wellness is the journey, not the destination.",
"Celebrate every small victory on your wellness journey.",
"A healthy outside starts from the inside.",
"Wellness is the first step to happiness.",
"Your body is a reflection of your lifestyle.",
"Progress, not perfection.",
"Choose health, happiness will follow.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a lifestyle, not a quick fix.",
"Progress, not perfection.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a journey, not a destination.",
"Choose health, happiness will follow.",
"Invest in your health – it pays the best interest.",
"Wellness is the key to a vibrant life.",
"Your health is your most valuable asset.",
"Love yourself enough to live a healthy lifestyle.",
"Wellness is the journey, not the destination.",
"Celebrate every small victory on your wellness journey.",
"A healthy outside starts from the inside.",
"Wellness is the first step to happiness.",
"Your body is a reflection of your lifestyle.",
"Progress, not perfection.",
"Choose health, happiness will follow.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a lifestyle, not a quick fix.",
"Progress, not perfection.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a journey, not a destination.",
"Choose health, happiness will follow.",
"Invest in your health – it pays the best interest.",
"Wellness is the key to a vibrant life.",
"Your health is your most valuable asset.",
"Love yourself enough to live a healthy lifestyle.",
"Wellness is the journey, not the destination.",
"Celebrate every small victory on your wellness journey.",
"A healthy outside starts from the inside.",
"Wellness is the first step to happiness.",
"Your body is a reflection of your lifestyle.",
"Progress, not perfection.",
"Choose health, happiness will follow.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a lifestyle, not a quick fix.",
"Progress, not perfection.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a journey, not a destination.",
"Choose health, happiness will follow.",
"Invest in your health – it pays the best interest.",
"Wellness is the key to a vibrant life.",
"Your health is your most valuable asset.",
"Love yourself enough to live a healthy lifestyle.",
"Wellness is the journey, not the destination.",
"Celebrate every small victory on your wellness journey.",
"A healthy outside starts from the inside.",
"Wellness is the first step to happiness.",
"Your body is a reflection of your lifestyle.",
"Progress, not perfection.",
"Choose health, happiness will follow.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a lifestyle, not a quick fix.",
"Progress, not perfection.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a journey, not a destination.",
"Choose health, happiness will follow.",
"Invest in your health – it pays the best interest.",
"Wellness is the key to a vibrant life.",
"Your health is your most valuable asset.",
"Love yourself enough to live a healthy lifestyle.",
"Wellness is the journey, not the destination.",
"Celebrate every small victory on your wellness journey.",
"A healthy outside starts from the inside.",
"Wellness is the first step to happiness.",
"Your body is a reflection of your lifestyle.",
"Progress, not perfection.",
"Choose health, happiness will follow.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a lifestyle, not a quick fix.",
"Progress, not perfection.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a journey, not a destination.",
"Choose health, happiness will follow.",
"Invest in your health – it pays the best interest.",
"Wellness is the key to a vibrant life.",
"Your health is your most valuable asset.",
"Love yourself enough to live a healthy lifestyle.",
"Wellness is the journey, not the destination.",
"Celebrate every small victory on your wellness journey.",
"A healthy outside starts from the inside.",
"Wellness is the first step to happiness.",
"Your body is a reflection of your lifestyle.",
"Progress, not perfection.",
"Choose health, happiness will follow.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a lifestyle, not a quick fix.",
"Progress, not perfection.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a journey, not a destination.",
"Choose health, happiness will follow.",
"Invest in your health – it pays the best interest.",
"Wellness is the key to a vibrant life.",
"Your health is your most valuable asset.",
"Love yourself enough to live a healthy lifestyle.",
"Wellness is the journey, not the destination.",
"Celebrate every small victory on your wellness journey.",
"A healthy outside starts from the inside.",
"Wellness is the first step to happiness.",
"Your body is a reflection of your lifestyle.",
"Progress, not perfection.",
"Choose health, happiness will follow.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a lifestyle, not a quick fix.",
"Progress, not perfection.",
"Your health is an investment, not an expense.",
"Nourish your body, feed your soul.",
"Celebrate progress, not perfection.",
"Your body is a reflection of your lifestyle.",
"Wellness is a journey, not a destination.",
"Choose health, happiness will follow.",
"Invest in your health – it pays the best interest.",
"Wellness is the key to a vibrant life.",
"Your health is your most valuable asset.",


    // Add more quotes as needed
  ];
}